Core_Network_Arch/urls.py
from django.conf.urls import url

from . import views

app_name = 'Core_Network_Arch'
urlpatterns = [
    # url(r'^$', views.IndexView.as_view(), name='index'),
    # url(r'^Report/Generating$', views.generate_report, name='generate_report'),
    url(r'^Report/$', views.ReportListView.as_view(), name='report_list'),
    url(r'^Report/([0-9]+)/$', views.ReportDetailView.as_view(), name='report_detail'),
    url(r'^Settings/$', views.SettingsMainView.as_view(), name='settings'),
    url(r'^Stats/(?P<pk>[0-9]+)/$', views.TrafficStatsDetailView.as_view(), name='trafficdetail'),
    # url(r'^TrafficDetail/RawData/(?P<pk>[0-9]+)/$', views.json_traffic_data_bulk, name='trafficdetail'),
    url(r'^TrafficDetail/BulkData$', views.json_traffic_data_bulk, name='trafficdetail'),
    url(r'^TrafficDetail/CreateTrafficStats$', views.create_single_traffic_data, name='create_stats'),
    url(r'^Report/CreateReport$', views.create_monthly_report, name='create_monthly_report')
]

Ip_Mgmt/urls.py
from django.conf.urls import url

from . import views

app_name = 'Ip_Mgmt'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='query_page'),
    url(r'^query', views.query_via_ip, name='query_via_ip'),
]

unmp/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from Core_Network_Arch import views
urlpatterns = [
    url(r'^$', views.IndexView.as_view()),
    url(r'^admin/', admin.site.urls),
    url(r'^Core_Network_Arch/', include('Core_Network_Arch.urls')),
    url(r'^Utils/ip/', include('Ip_Mgmt.urls')),

]

Core_Network_Arch/models.py
from django.db import models
from django.utils import timezone


class Farm(models.Model):
    type = models.CharField(max_length=50)
    display_priority = models.IntegerField(default=100)

    def __str__(self):
        return self.type


class DeviceLayerType(models.Model):
    layer = models.CharField(max_length=50)

    def __str__(self):
        return self.layer


class CactiServer(models.Model):
    name = models.CharField(max_length=20, unique=True)
    ip = models.GenericIPAddressField()
    username = models.CharField(max_length=20)
    password = models.CharField(max_length=20)
    port = models.IntegerField()

    def __str__(self):
        return self.name + '@' + str(self.ip)


class Device(models.Model):
    environment = models.ForeignKey(Farm, on_delete=models.CASCADE)
    layer = models.ForeignKey(DeviceLayerType, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    ip = models.CharField(max_length=20)
    accounting = models.BooleanField(blank=False, default=True)
    created_time = models.DateTimeField(auto_now_add=True)
    cactiServer = models.ForeignKey(CactiServer, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Link(models.Model):
    name = models.CharField(max_length=200, unique=True)
    description = models.CharField(max_length=200)
    type = models.CharField(max_length=2, choices=(('EX', 'External'), ('IN', 'Internal')), default='IN')
    accounting = models.BooleanField(blank=False, default=True)
    maximum_speed = models.FloatField(max_length=10)
    created_time = models.DateField(default=timezone.now)
    device = models.ManyToManyField(Device, through='DeviceLinkMember')

    def __str__(self):
        return self.name


class DeviceLinkMember(models.Model):
    link = models.ForeignKey(Link, on_delete=models.CASCADE)
    device = models.ForeignKey(Device, on_delete=models.CASCADE)
    data_source = models.BooleanField(default=False)
    graph_id = models.IntegerField(blank=True, null=True)

    def __str__(self):
        if self.data_source:
            return '%s in %s (graphing source)' % (self.link, self.device)
        else:
            return '%s in %s (non graphing source)' % (self.link, self.device)


class TrafficStatsReport(models.Model):
    name = models.CharField(max_length=20, unique=True)
    description = models.CharField(max_length=200)
    stats_interval = models.FloatField(max_length=10)
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    created_time = models.DateTimeField(auto_now_add=True)
    summary = models.TextField(max_length=2000,blank=True,default='无特殊说明')

    def __str__(self):
        return self.name


class TrafficStat(models.Model):
    name = models.CharField(max_length=200, unique=True)
    associated_report = models.ForeignKey(TrafficStatsReport, on_delete=models.CASCADE, null=True)
    data_source = models.ForeignKey(CactiServer, on_delete=models.SET_NULL, null=True)
    link = models.ForeignKey(Link, on_delete=models.CASCADE, null=False)
    type = models.CharField(max_length=20)
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    stats_interval = models.IntegerField()
    traffic_sequence = models.CharField(max_length=1000)
    created_time = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name

Core_Network_Arch/views.py
from django.http import HttpResponse, HttpResponseRedirect, QueryDict
from django.shortcuts import render, get_object_or_404
from django.core.urlresolvers import reverse
from django.views import generic
from .models import *
from django.utils import timezone
from Module.Core_Network_Arch.cacti import CactiDataAnalyzer
from django.contrib.auth.decorators import login_required,permission_required
import json
import datetime
import threading
import collections


# Create your views here.

class IndexView(generic.ListView):
    template_name = 'Core_Network_Arch/index.html'

    def get_queryset(self):
        return None


class ReportListView(generic.ListView):
    template_name = 'Core_Network_Arch/report_list_view.html'
    context_object_name = 'reports'

    def get_queryset(self):
        return TrafficStatsReport.objects.order_by('-id')


class ReportDetailView(generic.ListView):
    context_object_name = 'report_details'
    template_name = 'Core_Network_Arch/traffic_report.html'

    def get_queryset(self):
        link_list = []
        report = TrafficStatsReport.objects.get(id=self.args[0])
        farms = Farm.objects.order_by('-display_priority')
        print(farms)
        detail_dict = collections.OrderedDict()
        stats = TrafficStat.objects.filter(associated_report=report.id).order_by('name')
        devices = Device.objects.all()
        for farm in farms:
            detail_dict[farm.type] = {}

        for device in devices:
            if device.name not in detail_dict[device.environment.type]:
                detail_dict[device.environment.type][device.name] = []
        for stat in stats:
            detail_dict[stat.link.device.filter(devicelinkmember__data_source=True)[0].environment.type][stat.link.device.filter(devicelinkmember__data_source=True)[0].name].append(stat)
            if stat.link not in link_list:
                link_list.append(stat.link)
        print(detail_dict)
        return dict(report=report, detail_dict=detail_dict,links=link_list)


class SettingsMainView(generic.ListView):
    template_name = 'Core_Network_Arch/settings.html'
    context_object_name = 'settings'

    def get_queryset(self):
        return dict(type=Farm.objects.order_by('-id'), device=Device.objects.order_by('-id'),
                    link=Link.objects.order_by('-id'), device_layer_type=DeviceLayerType.objects.order_by('-id'),
                    trafficstatsReport=TrafficStatsReport.objects.order_by('-id'))


class TrafficStatsDetailView(generic.DetailView):
    template_name = 'Core_Network_Arch/traffic_stats_detail.html'
    model = TrafficStat


def json_traffic_data(request, pk):
    traffic_data = get_object_or_404(TrafficStat, pk=pk)
    if request.method == 'GET':
        # traffic_stats = get_object_or_404(TrafficStats, pk=traffic_stats_id)
        response_data = traffic_data.traffic_sequence
        return HttpResponse(json.dumps({'sequence': eval(response_data), 'month': 6}), content_type='application/json')


def json_traffic_data_bulk(request):
    if request.method == 'GET':
        bulk_list = []
        traffic_datas = TrafficStat.objects.filter(link=request.GET['link_id'],
                                                   associated_report=request.GET['report_id'])
        for traffic_data in traffic_datas:
            temp_sequence = eval(traffic_data.traffic_sequence)
            for sequence in temp_sequence:
                bulk_list.append(sequence)
        return HttpResponse(json.dumps({'sequence': bulk_list, 'month': 6}), content_type='application/json')


def create_single_traffic_data(request):
    if request.method == 'GET':
        if len(TrafficStat.objects.filter(start_time=datetime.datetime.fromtimestamp(float(request.GET['starttime'])),
                                          end_time=datetime.datetime.fromtimestamp(float(request.GET['endtime'])),
                                          stats_interval=request.GET['interval'],
                                          data_source=request.GET['cacti_id'],
                                          link=request.GET['link_id']
                                          )) != 0:
            return HttpResponse('Duplicate traffic stats.')
        if CactiServer.objects.get(pk=request.GET['cacti_id']) is None:
            return HttpResponse('No registered Cacti Server with id %s' % request.GET['cacti_id'])
        if Link.objects.get(pk=request.GET['link_id']) == 0:
            return HttpResponse('No registered Link with id %s' % request.GET['link'])
        if request.GET['year'] is None or request.GET['month'] is None:
            return HttpResponse('No specified month or year')
        else:
            starttime = datetime.datetime.fromtimestamp(float(request.GET['starttime']))
            endtime = datetime.datetime.fromtimestamp(float(request.GET['endtime']))
            cacti_server = CactiServer.objects.get(pk=request.GET['cacti_id'])
            link = Link.objects.get(pk=request.GET['link_id'])
            cactidataanalyzer = CactiDataAnalyzer()
            cactidataanalyzer.collect_cacti_data_monthly(cacti_server.ip, cacti_server.username,
                                                         cacti_server.password, link.graph_id,
                                                         request.GET['year'], request.GET['month'],
                                                         cacti_server.port)
            new_avg_traffic_stats = TrafficStat(
                name='%s-%s-%s@%s-avg' % (link.name, starttime, endtime, cacti_server.name),
                associated_report=None, data_source=cacti_server, link=link,
                start_time=starttime, end_time=endtime,
                stats_interval=request.GET['interval'], type='avg',
                traffic_sequence=cactidataanalyzer.get_avg_sequence())
            new_max_traffic_stats = TrafficStat(
                name='%s-%s-%s@%s-max' % (link.name, starttime, endtime, cacti_server.name),
                associated_report=None,
                data_source=cacti_server, link=link,
                start_time=starttime, end_time=endtime,
                stats_interval=request.GET['interval'], type='max',
                traffic_sequence=cactidataanalyzer.get_max_sequence())
            new_min_traffic_stats = TrafficStat(
                name='%s-%s-%s@%s-min' % (link.name, starttime, endtime, cacti_server.name),
                associated_report=None,
                data_source=cacti_server, link=link,
                start_time=starttime, end_time=endtime,
                stats_interval=request.GET['interval'], type='min',
                traffic_sequence=cactidataanalyzer.get_min_sequence())
            new_avg_traffic_stats.save()
            new_max_traffic_stats.save()
            new_min_traffic_stats.save()
        return HttpResponse('Successful!')


@permission_required('admin', login_url='/admin/')
def create_monthly_report(request):
    if request.method == 'GET':
        try:
            year = int(request.GET['report_time'].split('-')[0])
            month = int(request.GET['report_time'].split('-')[1])
            print(year,month)
        except ValueError:
            return HttpResponse('Invalid Month and Year!')
        start_time = datetime.datetime(year, month, 1)
        if month == 12:
            end_time = datetime.datetime(year + 1, 1, 1)
        elif month in range(1, 12):
            end_time = datetime.datetime(year, month + 1, 1)
        else:
            return HttpResponse('Invalid Month and Year!')
        if len(TrafficStatsReport.objects.filter(start_time=start_time, end_time=end_time)) != 0:
            return HttpResponse('指定月份的报表已经存在！如果需要重新生成，请于django管理后台删除当前月份报告，再重新生成。')
        created_report = TrafficStatsReport(name='%s年%s月流量资源报表'%(year,month),start_time=start_time, end_time=end_time,description='%s年%s月流量资源报表'%(year,month),stats_interval=86400)
        created_report.save()
        for link in Link.objects.filter(accounting=True):
            t = threading.Thread(target=_create_single_stats_monthly, args=(link, year, month, start_time, end_time,created_report))
            t.start()
        return HttpResponse('已经成功提交生成报告。请等待大约1分钟后打开报表。')


def _create_single_stats_monthly(link, year, month,starttime,endtime,report):
    cactidataanalyzer = CactiDataAnalyzer()
    # print(link)
    print(DeviceLinkMember.objects.filter(data_source=True, link=link))
    designated_source = DeviceLinkMember.objects.filter(data_source=True, link=link)[0]
    cacti_server = designated_source.device.cactiServer
    cactidataanalyzer.collect_cacti_data_monthly(cacti_server.ip, cacti_server.username,
                                                 cacti_server.password, designated_source.graph_id,
                                                 year, month,
                                                 cacti_server.port)
    start_timestamp = datetime.datetime(year, month, 1).timestamp()
    new_max_traffic_stats = TrafficStat(
                name='%s-%s-%s@%s-max' % (link.name, starttime, endtime, cacti_server.name),
                associated_report=report,
                data_source=cacti_server, link=link,
                start_time=starttime, end_time=endtime,
                stats_interval=86400, type='max',
                traffic_sequence=cactidataanalyzer.get_max_sequence())
    new_min_traffic_stats = TrafficStat(
                name='%s-%s-%s@%s-min' % (link.name, starttime, endtime, cacti_server.name),
                associated_report=report,
                data_source=cacti_server, link=link,
                start_time=starttime, end_time=endtime,
                stats_interval=86400, type='min',
                traffic_sequence=cactidataanalyzer.get_min_sequence())
    new_avg_traffic_stats = TrafficStat(
                name='%s-%s-%s@%s-avg' % (link.name, starttime, endtime, cacti_server.name),
                associated_report=report, data_source=cacti_server, link=link,

Core_Network_Arch/templates/Core_Network_Arch/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'Core_Network_Arch/css/index.css' %}" />
    <title>Network Management Platform</title>
</head>
<body>
    <h1 style="text-align:center" id="title">管理平台</h1>
    <div id="main_box">
        <div class="wrapper" id="core"><h2><a href="{% url 'Core_Network_Arch:report_list' %}">网络流量报表程序</a></h2></div>
        <div class="wrapper" id="query_page"><h2><a href="{% url 'Ip_Mgmt:query_page' %}">IP段特殊地址查询</a></h2></div>
        <div class="wrapper" id="query_page"><h2><a href="{% url 'admin:index' %}">管理平台登录入口</a></h2></div>
    </div>


</body>
</html>

Core_Network_Arch/templates/Core_Network_Arch/report_list_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% if reports %}
    <h1>流量报告列表</h1>
    <ul>
    {% for report in reports %}
        <li>{{forloop.counter}} {{report}} 创建日期:{{report.created_time}}<a class="report_list" href="{% url 'Core_Network_Arch:report_detail' report.id %}">详细信息</a></li>
        {% endfor %}
    </ul>
    {% endif %}
    <h1>报告生成管理</h1>
    <form action="{% url 'Core_Network_Arch:create_monthly_report' %}" method="get">
        <label for="year_month">需要生成报表的月份</label>
        <input id="report_time" type="month" name="report_time">
        <input type="submit" value="生成报告">
    </form>
</body>
</html>

Core_Network_Arch/templates/Core_Network_Arch/traffic_report.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'Core_Network_Arch/css/style.css' %}" />
    <script type="text/javascript" src="{% static 'Core_Network_Arch/js/jquery-1.12.4.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'Core_Network_Arch/js/common.js' %}"></script>
    <script type="text/javascript" src="{% static 'Core_Network_Arch/js/hc/js/highcharts.js' %}"></script>
    <!--<script type="text/javascript" src="{% static 'Core_Network_Arch/js/hc/js/modules/exporting.js' %}"></script>-->
    <script type="text/javascript" src="{% static 'Core_Network_Arch/js/hc/js/themes/sand-signika.js' %}"></script>
    <script type="text/javascript" src="{% static 'Core_Network_Arch/js/draw.js' %}"></script>
    <script type="text/javascript">
    {% for link in report_details.links %}
        $.get("/Core_Network_Arch/TrafficDetail/BulkData",{link_id:{{ link.id }},report_id:{{ report_details.report.id }}},function (result){
        draw_monthly(result,{{link.id}},"{{link.name}}({{link.description}})",{{link.maximum_speed}})
        })
    {% endfor %}

    </script>
    <meta charset="UTF-8">
    <title>{{report_details.report.name}}</title>
</head>
<body>
<div id="report_header">
    <div id="global_header">
    </div>
    <h1>{{report_details.report.name}}</h1>
    <ol>
        {% for farm, device_dict in report_details.detail_dict.items %}
        <li><a href="#farm_{{forloop.counter}}">{{farm}}</a></li>
        {% endfor %}
        <li><a href="#remark">报表备注与小结</a></li>
    </ol>

</div>
<hr id="top_split">
<div id="main_wrapper">
{% for farm, device_dict in report_details.detail_dict.items %}
<div class="farm_box" id="farm_{{ forloop.counter }}"><h2 class="farm">{{ farm }}</h2>
    {% if not device_dict %}
        <span class="notification">暂无设备被加入该域下进行统计</span>
    {% else %}
        {% for device,stats in device_dict.items %}
            <div class="device_box"><h3 class="device">{{ device }}</h3>
            {% if not stats %}
               <span class="notification">暂无链路被加入到该设备下进行统计</span>
            {% else %}
               {% for stat in stats %}
                  <div class="GraphBox" id="container_{{ stat.link.id }}"></div>
               {% endfor %}
            {% endif %}
            </div>
        {% endfor %}
    {% endif %}
</div>
    <hr>
{% endfor %}
    <div id="remark">
        <h2 id="remark_title">报表备注与小结</h2>
        <p id="summary_text">
            {{ report_details.report.summary }}
        </p>
    </div>
</div>
<p class="footer">太平洋网络网络系统部网络组制</p>
    <!--{% for device in report_details.detail_dict.farm %}-->
    <!--<p>{{ device }}</p>-->
        <!--{% for link in report_details.detail_dict.farm.device %}-->
        <!--<p>{{ link }}</p>-->
        <!--<div class="GraphBox" id="container_{{ link.id }}"></div>-->
        <!--{% endfor %}-->
    <!--{% endfor %}-->


</body>
</html>

Core_Network_Arch/templates/Core_Network_Arch/traffic_stats_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'Core_Network_Arch/css/style.css' %}" />
    <script type="text/javascript" src="{% static 'Core_Network_Arch/js/jquery-1.12.4.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'Core_Network_Arch/js/common.js' %}"></script>
    <script type="text/javascript" src="{% static 'Core_Network_Arch/js/hc/js/highcharts.js' %}"></script>
    <script type="text/javascript" src="{% static 'Core_Network_Arch/js/hc/js/modules/exporting.js' %}"></script>
    <script type="text/javascript" src="{% static 'Core_Network_Arch/js/draw.js' %}"></script>
    <script type="text/javascript">
    {% for %}
    $.get("http://127.0.0.1:8000/Core_Network_Arch/TrafficDetail/BulkData",{link_id:1,report_id:1},function (result){
        draw_monthly(result)
    })
    </script>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div id="container"></div>
</body>
</html>